version: "3.7"
services:
    postgres:
        image: postgres:15.3-alpine3.18
        container_name: "postgres"
        restart: unless-stopped
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - ./db-data:/var/lib/postgresql/data
        command: ["postgres", "-c", "log_statement=all", "-c", "logging_collector=on"]

volumes:
    db-data:
        driver: local